import json

# Manual translation dictionary for accuracy
translation_map = {
    # Categories
    "الافطار من (8ص الى 1م)": "Breakfast (8 AM to 1 PM)",
    "الغداء (من الساعه 1م)": "Lunch (From 1 PM)",
    "التحليه": "Desserts",
    "مشروبات ساخنه": "Hot Drinks",
    "العصائر": "Juices",
    
    # Subcategories
    "المقبلات": "Appetizers",
    "السلاطات": "Salads",
    "الشوربات": "Soups",
    "باستا": "Pasta",
    "ريزوتو": "Risotto",
    "صفايح": "Safiha",
    "بيتزا": "Pizza",
    "سندوتشات": "Sandwiches",
    "غربي اسماك وبحريات": "Seafood",
    "وجبات اطفال": "Kids' Meals",
    "المطبخ الشرقي": "Oriental Cuisine",
    "كريب حار": "Salty Crepe",
    "غربي اللحوم": "Meat Selection",
    "غربي الدجاج": "Chicken Selection",
    "وجبات فاهيتا": "Fajita Meals",
    "المخيتو": "Mojitos",
    "ميلك شيك": "Milkshakes",
    "سموثي": "Smoothies",
    "مشروبات معلبه": "Canned Drinks",
    "ايس كافي": "Iced Coffee",
    "ايس تي": "Iced Tea",
    "فرابتشينو": "Frappuccino",
    "هوت شوكلت": "Hot Chocolate",
    "العصائر": "Fresh Juices",
    
    # Breakfast Items
    "ﻻﻓﻴﻨﺎ": "Lavina",
    "ﻻﻓﻴﻨﺎ (ﻋﺎئلي)": "Lavina (Family)",
    "ﻛﻮﻧﺘﻴﻨﻨﺘﺎل": "Continental",
    "افطار مغربي": "Moroccan Breakfast",
    "شرقي": "Oriental Breakfast",
    "صحن قلايه": "Qallaya Plate",
    "ﺷﻜﺸﻮﻛﺔ ﺗﺮﻛﻴﺔ": "Turkish Shakshouka",
    "ﺷﻜﺸﻮﻛﺔ ﻣﺮﻗﺎز": "Merguez Shakshouka",
    "ﺷﻜﺸﻮﻛﺔ ﻗﺪﻳﺪ": "Qadeed Shakshouka",
    "أوﻣﻠﻴﺖ ﻛﻼﺳﻴﻚ": "Classic Omelette",
    "أوﻣﻠﻴﺖ ﺑﺎﻟﺠﺒﻨﺔ": "Cheese Omelette",
    "أوﻣﻠﻴﺖ ﺧﻀﺮوات": "Veggie Omelette",
    "أوﻣﻠﻴﺖ ﻓﻘﺎع": "Mushroom Omelette",
    "ﺗﻮﺳﺖ ﺟﺒﻨﺔ": "Cheese Toast",
    "ﺗﻮﺳﺖ ﺗﻮﻧﺔ": "Tuna Toast",
    "ﺗﻮﺳﺖ ﺑﻴﺾ": "Egg Toast",
    "ﺗﻮﺳﺖ ﺑﺒﺮوﻧﻲ": "Pepperoni Toast",
    "سكرامبل بيض": "Scrambled Eggs",
    "بيض بينديكت": "Eggs Benedict",
    "بيجلز": "Bagels",
    "اﻷﻓﻄﺎر اﻟﺼﺤﻲ 2": "Healthy Breakfast 2",
    "اﻷﻓﻄﺎر اﻟﺼﺤﻲ": "Healthy Breakfast",
    "صحن شوفان": "Oatmeal Bowl",
    "إﺿﺎﻓﺎت -- ﺻﺤﻦ اﻟﺠﺒﻦ": "Extras - Cheese Plate",
    "اضافات -- اﻟﺰﻋﺘﺮ ﻣﻊ زﻳﺖ اﻟﺰﻳﺘﻮن": "Extras - Zaatar with Olive Oil",
    "زعتر وزيت زيتون": "Zaatar and Olive Oil",
    "التحلية": "Desserts",
    "التحليه": "Desserts",
    "كريب حار": "Salty Crepe",

    # Appetizers
    "ﺑﺮوﺳﻜﻴﺘﺎ": "Bruschetta",
    "ﺑﻮرﻳﻚ ﻟﺤﻢ": "Meat Bourek",
    "ﻛﺒﺔ ﻟﺤﻢ (4 ﻗﻄﻊ)": "Meat Kibbeh (4 Pieces)",
    "ﻣﻮزارﻳﻼ ﻓﻴﻨﻘﺮ": "Mozzarella Fingers",
    "ﻓﺶ ﻓﻴﻨﻘﺮ": "Fish Fingers",
    "ﺻﺤﻦ ﺑﻄﺎﻃﺎ": "Potato Fries Plate",
    "ﺳﻤﺒﻮﺳﺔ ﺑﺎﻟﺠﺒﻨﺔ": "Cheese Sambousek",
    "ﺗﺸﻜﻴﻦ ﺳﺘﺮﻳﺒﺲ": "Chicken Strips",
    "بسطيلا دجاج": "Chicken Pastilla",
    "سوتي فواكه البحر": "Seafood Sauté",
    "صحن لاڤينا مشكل": "Lavina Mixed Plate",

    # Salads
    "ﺳﻼﻃﺔ ﻋﺮﺑﻴﺔ": "Arabic Salad",
    "ﺳﻼﻃﺔ ﺣﻤﺺ": "Hummus Salad",
    "ﺳﻼﻃﺔ ﻛﻮل ﺳﻠﻮ": "Coleslaw Salad",
    "ﺳﻼﻃﺔ ﺟﺮﺟﻴﺮ": "Arugula Salad",
    "ﺳﻼﻃﺔ ﻣﺸﻮﻳﺔ": "Grilled Salad",
    "ﺳﻼﻃﺔ ﺑﺎﺑﺎ ﻏﻨﻮش": "Baba Ganoush Salad",
    "ﺳﻼﻃﺔ ﺳﻴﺰر": "Caesar Salad",
    "ﺳﻼﻃﺔ ﻳﻮﻧﺎﻧﻴﺔ": "Greek Salad",
    "ﺳﻼﻃﺔ ﻓﺘﻮش": "Fattoush Salad",
    "ﺳﻼﻃﺔ ﻓﻮاﻛﺔ اﻟﺒﺤﺮ": "Seafood Salad",
    "ﺳﻼﻃﺔ ﻻﻓﻴﻨﺎ": "Lavina Salad",

    # Soups
    "ﺷﻮرﺑﺔ اﻟﻌﺪس": "Lentil Soup",
    "ﺷﻮرﺑﺔ اﻟﺪﺟﺎج ﺑﺎﻟﻔﻘﺎع": "Chicken Mushroom Soup",
    "ﺷﻮرﺑﺔ اﻟﺠﻤﺒﺮي": "Shrimp Soup",

    # Pasta
    "ﺑﺎﺳﺘﺎ أرﺑﻴﺎﺗﺎ": "Pasta Arrabbiata",
    "ﺑﻴﺴﺘﻮ ﻓﻮزﻳﻠﻰ": "Pesto Fusilli",
    "ﺑﻮﻟﻮﻧﻴﺰ": "Bolognese",
    "اﻟﻔﺮﻳﺪو ﺑﺎﻟﺪﺟﺎج": "Chicken Alfredo",
    "ﺳﺒﺎﻗﻴﺘﻲ ﺑﺎﻟﻔﻮاﻛﺔ اﻟﺒﺤﺮ": "Seafood Spaghetti",
    "لانجويني قمبري": "Shrimp Linguine",
    "ﻻزاﻧﻴﺎ ﺑﻠﻮﻧﻴﺰ": "Bolognese Lasagna",
    "بشاميل دجاج": "Chicken Béchamel",

    # Risotto
    "روزوﺗﻮ ﻣﺸﺮوم": "Mushroom Risotto",
    "روزوﺗﻮ ﺳﻲ ﻓﻮد": "Seafood Risotto",

    # Safiha
    "ﺻﻔﻴﺤﺔ ﻟﺤﻢ": "Meat Safiha",
    "ﺻﻔﻴﺤﺔ ﺟﺒﻨﺔ": "Cheese Safiha",
    "ﺻﻔﻴﺤﺔ ﺑﺠﺒﻨﺔ وﻟﺤﻢ": "Cheese and Meat Safiha",
    "ﺻﻔﻴﺤﺔ زﻋﺘﺮ": "Zaatar Safiha",
    "صفيحة زﻋﺘﺮ وﺟﺒﻨﺔ": "Zaatar and Cheese Safiha",
    "ﺻﻔﻴﺤﺔ ﻟﺤﻢ ﻣﻊ ﺟﺒﻨﺔ وزﻋﺘﺮ": "Meat Safiha with Cheese and Zaatar",
    "ﺻﻔﻴﺤﺔ ﺣﺠﻢ ﻋﺎﺋﻠﻲ": "Family Size Safiha",

    # Pizza
    "ﻣﺎرﺟﺎرﻳﺘﺎ": "Margherita",
    "ﺧﻀﺎر": "Vegetable",
    "ﻓﻘﺎع": "Mushroom",
    "ﺗﻮﻧﺔ": "Tuna",
    "ﺑﻴﺘﺰا رﻳﺠﻴﻨﺎ": "Regina Pizza",
    "ﺑﻴﺘﺰا ﺑﻴﺴﺘﻮ": "Pesto Pizza",
    "ﺑﻴﺘﺰا ﻛﻮاﺗﺮو ﻓﻮرﻣﺎﺟﻲ": "Quattro Formaggi Pizza",
    "ﺑﻴﺘﺰا دﺟﺎج": "Chicken Pizza",
    "ﺑﻴﺘﺰا ﺑﻴﺎﻧﻜﺎ": "Bianca Pizza",
    "ﺑﻴﺘﺰا ﻻﻓﻴﻨﺎ": "Lavina Pizza",

    # Sandwiches
    "سندوتش ﻓﺎﻫﻴﺘﺎ دﺟﺎج": "Chicken Fajita Sandwich",
    "ﻓﺎﻫﻴﺘﺎ ﻟﺤﻢ": "Beef Fajita",
    "ﻣﻴﻨﻲ ﺑﺮﺟﺮ ﻟﺤﻢ": "Mini Beef Burger",
    "ﻛﻠﻮب ﺳﻨﺪوﺗﺶ": "Club Sandwich",
    "ﺑﺮﺟﺮ ﻟﺤﻢ": "Beef Burger",
    "ﺑﺎﻗﻴﺖ دﺟﺎج ﻣﺸﻮي": "Grilled Chicken Baguette",

    # Seafood
    "قاروص مشوي": "Grilled Sea Bass",
    "ﺳﻲ ﺑﺎس ﻓﻴﻠﻴﺔ": "Sea Bass Fillet",
    "ﺟﻤﺒﺮي ﻣﺸﻮي": "Grilled Shrimp",
    "ﺷﺮاﺋﺢ وراثة ﻣﻊ ﺻوص اﻟليمون": "Bream Slices with Lemon Sauce",
    "ﺑﺎﻳﻼ": "Paella",
    "ﻣﺸﻜﻞ ﻻﻓﻴﻨﺎ أﺳﻤﺎك": "Lavina Seafood Mix",

    # Kids
    "ﺗﺸﻜﻴﻦ ﻧﺎﺟﻴﺖ": "Chicken Nuggets",

    # Oriental
    "ﺷﻴﺶ ﻃﺎووق": "Shish Taouk",
    "ﻛﺒﺎب دﺟﺎج": "Chicken Kebab",
    "ﻧﺺ دﺟﺎج ﻣﺸﻮي": "Half Grilled Chicken",
    "ﻛﺒﺎب ﻟﺤﻢ": "Meat Kebab",
    "ﺷﻴﺶ ﻟﺤﻢ ﺧﺮوف": "Lamb Shish",
    "أرﻳﺎش ﺧﺮوف": "Lamb Chops",
    "ﻛﺒﺎب ادﻧﺎ ﺣﺎر": "Spicy Adana Kebab",
    "ﻛﺒﺎب ﺑﺎﻟﺠﺒﻨﺔ": "Cheese Kebab",
    "ﺟﻮاﻧﺢ دﺟﺎج ﻣﺸﻮي": "Grilled Chicken Wings",
    "ﻓﺨﺪة دﺟﺎج ﻣﺸﻮي": "Grilled Chicken Thigh",
    "ﻛﺒﺎب اورﻓﻠﻲ": "Urfali Kebab",
    "ﻣﺸﻜﻞ 2 اسياخ": "Mixed 2 Skewers",
    "مشكل 3 اسياخ": "Mixed 3 Skewers",
    "مشكل 4 اسياخ": "Mixed 4 Skewers",
    "ﻣﺸﻜﻞ 5 اﺳﻴﺎخ": "Mixed 5 Skewers",
    "ﻣﺸﻜﻞ 8 ﺳﻴﺎخ": "Mixed 8 Skewers",
    "ﻣﺸﻜﻞ مشاوي ﻻﻓﻴﻨﺎ ﻋﺎﺋﻠﻲ": "Lavina Family Grill Mix",

    # Crepe
    "كريب أجبان": "Cheese Crepe",
    "ﻛﺮﻳﺐ دﺟﺎج": "Chicken Crepe",
    "ﻛﺮﻳﺐ ﺗﻮﻧﺔ": "Tuna Crepe",

    # Meat
    "فيليه صوص ماشروم": "Fillet with Mushroom Sauce",
    "فيليه صوص ليمون": "Fillet with Lemon Sauce",
    "فيليه بصلصة الفلفل الأسود": "Fillet with Black Pepper Sauce",
    "تي بون": "T-Bone Steak",
    "فيليه المينيون": "Filet Mignon",
    "أرﻳﺎش ﺧﺮوف ﻣﻊ ﺻﻮص ﻟﻴﻤﻮن": "Lamb Chops with Lemon Sauce",
    "ﻓﻴﻠﻴه صوص ﺟﺮﻳﻔﻲ": "Fillet with Gravy Sauce",
    "ﻓﻴﻠﻴﺔ ﺻﻮص ﻃﻤﺎﻃﻢ والجبن": "Fillet with Tomato and Cheese Sauce",
    "ﻓﻴﻠﻴﺔ مشوي": "Grilled Fillet",

    # Chicken
    "ﺗﺸﻜﻴﻦ ﺑﺮﻳﺴﺖ ﺻﻮص ﻣﺎﺷﺮوم": "Chicken Breast with Mushroom Sauce",
    "ﺗﺸﻜﻴﻦ ﺑﺮﻳﺴﺖ ﺑﺎﻧﻲ": "Chicken Breast Pane",
    "ﺗﺸﻜﻴﻦ ﺑﺮﻳﺴﺖ ﺻﻮص ﻟﻴﻤﻮن": "Chicken Breast with Lemon Sauce",
    "رول دﺟﺎج ﺑﺎﻟﺴﺒﺎﻧﺦ واﻟﻤﻮزارﻳﻼ": "Chicken Roll with Spinach and Mozzarella",
    "ﻛﻮردون ﺑﻠﻮ": "Cordon Bleu",
    "تشيكن بريست": "Chicken Breast",

    # Fajita meals
    "وجبة فاهيتا دجاج": "Chicken Fajita Meal",
    "وجبة فاهيتا لحم": "Beef Fajita Meal",
    "وجبة فاهيتا مكس": "Mixed Fajita Meal",

    # Desserts
    "ﻛﺮﻳﺐ ﺳﻮﺷﻲ": "Sushi Crepe",
    "ﻛﺮﻳﺐ ﻓﻮاﻛﺔ": "Fruit Crepe",
    "ﻛﺮﻳﺐ اﻳﺲ ﻛﺮﻳﻢ": "Ice Cream Crepe",
    "ﻛﺮﻳﺐ رول": "Crepe Roll",
    "كريب فيوتوتشيني": "Fettuccine Crepe",
    "ﻛﺮﻳﺐ ﺗﺎم": "Tam Crepe",
    "ﻛﺮﻳﺐ ﻓﺴﺘﻖ": "Pistachio Crepe",
    "ﻛﺮﻳﺐ ﺑﻨﺪق": "Hazelnut Crepe",
    "ﻛﺮﻳﺐ ﻟﻮز": "Almond Crepe",
    "كريب نوتيلا": "Nutella Crepe",
    "ﻛﺮواﺳﻮن ﻧﻮﺗﻴﻼ": "Nutella Croissant",
    "ﻛﺮواﺳﻮن ﺟﺒﻨﺔ": "Cheese Croissant",
    "ﻛﺮواﺳﻮن ﻋﺴﻞ": "Honey Croissant",
    "ﻛﺮواﺳﻮن ﻧﻮﺗﻴﻼ + ﻋﺴﻞ + ﻟﻮز": "Nutella + Honey + Almond Croissant",
    "ﻣﺘﺮد ﺷﺮﻗﻲ ﻣﺸﻜﻞ ﻛﺒﻴﺮ": "Large Oriental Mixed Plate",
    "ﻣﺘﺮد ﺷﺮﻗﻲ ﻣﺸﻜﻞ ﺻﻐﻴﺮ": "Small Oriental Mixed Plate",
    "ﻓﻄﻴﺮة ﻣﻐﺮﺑﻴﺔ": "Moroccan Pie",
    "ﺻﺤﻦ ﻓﻮاﻛﺔ ﻣﺸﻜﻠﺔ - كبير": "Large Mixed Fruit Plate",
    "ﺻﺤﻦ ﻓﻮاﻛﺔ ﻣﺸﻜﻠﺔ - وسط": "Medium Mixed Fruit Plate",
    "ﻛﻴﻚ ﻻﻓﻴﻨﺎ": "Lavina Cake",
    "ﺳﺎن ﺳﺒﺎﺳﺘﻴﺎن": "San Sebastian",
    "ﺑﺮاوﻧﻴيز أﻳﺲ ﻛﺮﻳﻢ": "Brownies with Ice Cream",
    "واﻓﻞ ﻛﻼﺳﻴﻚ": "Classic Waffle",
    "واﻓﻞ ﻟﻮز وﻋﺴﻞ": "Almond and Honey Waffle",
    "واﻓﻞ اﻳﺲ ﻛﺮﻳﻢ": "Ice Cream Waffle",
    "واﻓﻞ ﻓﻮاﻛﺔ": "Fruit Waffle",
    "واﻓﻞ ﻓﺴﺘﻖ": "Pistachio Waffle",
    "واﻓﻞ ﺑﻨﺪق": "Hazelnut Waffle",
    "واﻓﻞ ﻧﻮﺗﻴﻼ": "Nutella Waffle",
    "ﻣﻨﻲ ﺑﺎن ﻛﻴﻚ ﻟﻮز": "Mini Almond Pancake",
    "ﻣﻨﻲ ﺑﺎن ﻛﻴﻚ رﻳيد ﻓﻴﻠﻔﻴﺖ": "Mini Red Velvet Pancake",
    "ﻣﻨﻲ ﺑﺎن ﻛﻴﻚ ﻓﻮاﻛﺔ": "Mini Fruit Pancake",
    "ﻣﻨﻲ ﺑﺎن ﻛﻴﻚ ﻟﻮﺗﺲ": "Mini Lotus Pancake",
    "ﻣﻨﻲ ﺑﺎن ﻛﻴﻚ اورﻳﻮ": "Mini Oreo Pancake",
    "ﻣﻨﻲ ﺑﺎن ﻛﻴﻚ ﻓﺴﺘﻖ": "Mini Pistachio Pancake",
    "ﻣﻨﻲ ﺑﺎن ﻛﻴﻚ ﻧﻮﺗﻴﻼ": "Mini Nutella Pancake",
    "ﺑﺎن ﻛﻴﻚ ﻛﻼﺳﻴﻚ": "Classic Pancake",
    "ﺑﺎن ﻛﻴﻚ رﻳيد ﻓﻴﻠﻔﻴﺖ": "Red Velvet Pancake",
    "ﺑﺎن ﻛﻴﻚ ﻓﻮاﻛﺔ": "Fruit Pancake",
    "بان ﻛﻴﻚ ﻓﺴﺘﻖ": "Pistachio Pancake",
    "ﺑﺎن ﻛﻴﻚ ﻟﻮﺗﺲ": "Lotus Pancake",
    "ﺑﺎن ﻛﻴﻚ ﻧﻮﺗﻴﻼ": "Nutella Pancake",

    # Hot Drinks
    "بستاشيو": "Pistachio",
    "ﻟﻮﺗﺲ": "Lotus",
    "ﺷﻮﻛﻠﺖ": "Chocolate",
    "مارشميلو": "Marshmallow",
    "براد شاهي صغير مكسرات": "Small Tea Pot with Nuts",
    "براد شاهي كبير مكسرات": "Large Tea Pot with Nuts",
    "أﺳﺒﺮﻳﺴﻮ": "Espresso",
    "اﻣﺮﻳﻜانو": "Americano",
    "ﺳﺒﻴﺴﻴﺎل": "Special",
    "ﻓﻼت واﻳﺖ": "Flat White",
    "ﻛﺎﺑﺘﺸﻴﻨﻮ": "Cappuccino",
    "ﻧﺴﻜﺎﻓﻴﺔ": "Nescafe",
    "ﻛﻮرﺗﺎدو": "Cortado",
    "ﻣﻜﻴﺎﺗﻮ": "Macchiato",
    "ﻛﺮاﻣﻴﻞ ﻣﻜﻴﺎﺗﻮ": "Caramel Macchiato",
    "أﻓﻮﻛﺎﺗو": "Affogato",
    "ﻛﺎﻓﻲ ﻣﻮﻛﺎ": "Caffe Mocha",
    "ﻛﺎﻓﻲ لاتيه": "Caffe Latte",
    "ﺳﺒﺎﻧﺶ ﻻﺗﻲ": "Spanish Latte",
    "ﺳﺒﺎﻧﺶ ﻻﺗﻲ ﻛﺮاﻣﻴﻞ": "Caramel Spanish Latte",
    "ﻗﻬﻮة ﻋﺮﺑﻴﺔ": "Arabic Coffee",
    "ﺷﺎي": "Tea",

    # Juices & Cold
    "ﻋﺼﻴﺮ ﻓﺮاوﻟﺔ": "Strawberry Juice",
    "ﻋﺼﻴﺮ ﺑﺮﺗﻘﺎل": "Orange Juice",
    "ﻋﺼﻴﺮ ﻟﻴﻤﻮن وﻧﻌﻨﺎع": "Lemon with Mint Juice",
    "ﻋﺼﻴﺮ ﻣﺎﻧﺠﺎ": "Mango Juice",
    "ﻋﺼﻴﺮ ﻛﻴﻮي": "Kiwi Juice",
    "ﻋﺼﻴﺮ أﻧﺎﻧﺎس": "Pineapple Juice",
    "ﻋﺼﻴﺮ أﻓﻮﻛﺎدو": "Avocado Juice",
    "ﻓﺮوبي": "Froopy",
    "ﻛﻮﻛﺘﻴﻞ": "Cocktail",
    "موخيتو فواكه": "Fruit Mojito",
    "ﻣوﺨﻴﺘﻮ ﻫﺎواي": "Hawaii Mojito",
    "ﻣوﺨﻴﺘﻮ ﺑﻼك ﻣﻮن": "Black Moon Mojito",
    "موخيتو بيناكولاده": "Pina Colada Mojito",
    "ﻣوﺨﻴﺘﻮ ﻣﻮﻧﺘﺎﻧﺎ": "Montana Mojito",
    "ﻣوﺨﻴﺘﻮ روز": "Rose Mojito",
    "موخيتو باشن فروت": "Passion Fruit Mojito",
    "ﻣﻴﻠﻚ ﺷﻴﻚ ﻓﺎﻧﻴﻠﻴﺎ": "Vanilla Milkshake",
    "ميلك شيك شوكلاتة": "Chocolate Milkshake",
    "ﻣﻴﻠﻚ ﺷﻴﻚ ﻧﻮﺗﻴﻼ": "Nutella Milkshake",
    "ﻣﻴﻠﻚ ﺷﻴﻚ ﻟﻮﺗﺲ": "Lotus Milkshake",
    "ﻣﻴﻠﻚ ﺷﻴﻚ ﻓﺴﺘﻖ": "Pistachio Milkshake",
    "ﺳﻤﻮﺛﻲ ﻓﺮاوﻟﺔ": "Strawberry Smoothie",
    "ﺳﻤﻮﺛﻲ ﻣﺎﻧﺠﻮ": "Mango Smoothie",
    "ﺳﻤﻮﺛﻲ ﺑﺎﺷﻦ ﻓﺮوت": "Passion Fruit Smoothie",
    "ﺳﻤﻮﺛﻲ ﺗﻮت ﺑﺮي": "Blueberry Smoothie",
    "ﺳﻤﻮﺛﻲ ﻛﺮز": "Cherry Smoothie",
    "ﺳﻤﻮﺛﻲ ﻣﻮز": "Banana Smoothie",
    "مشروب غازي": "Soft Drink",
    "ﻣﺸﺮوب ﺟﺮﻳﻴﻦ": "Green Drink",
    "ﻋﺼﻴﺮ ﺳﺒﺎﻳﺘﺰ": "Spaitz Juice",
    "ﻣﺎء ﻏﺎزي زﺟﺎﺟﻴﺔ": "Sparkling Water (Glass)",
    "ﻣﺎء ﻣﻌﺪﻧﻴﺔ زﺟﺎﺟﻴﺔ": "Mineral Water (Glass)",
    "ايس كافي عادي": "Regular Iced Coffee",
    "ايس كافي نكهة": "Flavored Iced Coffee",
    "ايس تي": "Iced Tea",
    "فرابتشينو": "Frappuccino",
    "ﻫﻮت ﺷﻮﻛﻠﺖ": "Hot Chocolate",
    "هوت شوكلت": "Hot Chocolate",
    "ﺑﺴﺘﺎﺷﻴﻮ": "Pistachio",
    "ﻟﻮﺗﺲ": "Lotus",
    "ﺷﻮﻛﻠﺖ": "Chocolate",
    "مارشميلو": "Marshmallow",
    "أﻓﻮﻛﺎﺗﻮ": "Affogato",
    "أﺳﺒﺮﻳﺴﻮ": "Espresso",
    "اﻣﺮﻳﻜﺎﻧﻮ": "Americano",
    "اﻣﺮﻳﻜانو": "Americano",
    "أﻓﻮﻛﺎﺗو": "Affogato",
    "ﻓﺮوبي": "Froopy",
    "ﻓﺮوﺑﻲ": "Froopy",
    "ﻛﻴﻚ ﻻﻓﻴﻨﺎ": "Lavina Cake",
    "ﺳﺎن ﺳﺒﺎﺳﺘﻴﺎن": "San Sebastian",
    "ﺑﺮاوﻧﻴﺰ أﻳﺲ ﻛﺮﻳﻢ": "Brownies with Ice Cream",
    "ﺑﺮاوﻧﻴيز أﻳﺲ ﻛﺮﻳﻢ": "Brownies with Ice Cream",
    "ﻣﻨﻲ ﺑﺎن ﻛﻴﻚ رﻳﺪ ﻓﻴﻠﻔﻴﺖ": "Mini Red Velvet Pancake",
    "ﻣﻨﻲ ﺑﺎن ﻛﻴﻚ رﻳيد ﻓﻴﻠﻔﻴﺖ": "Mini Red Velvet Pancake",
    "ﺑﺎن ﻛﻴﻚ رﻳﺪ ﻓﻴﻠﻔﻴﺖ": "Red Velvet Pancake",
    "ﺑﺎن ﻛﻴﻚ رﻳيد ﻓﻴﻠﻔﻴﺖ": "Red Velvet Pancake",
    "بان ﻛﻴﻚ ﻓﺴﺘﻖ": "Pistachio Pancake",
    "ﺑﺎن ﻛﻴﻚ ﻓﺴﺘﻖ": "Pistachio Pancake",
    "المخيتو": "Mojitos",
    "ميلك شيك": "Milkshakes",
    "سموثي": "Smoothies",
    "مشروبات معلبه": "Canned Drinks",
    "ايس كافي": "Iced Coffee",
    "ايس تي": "Iced Tea",
    "فرابتشينو": "Frappuccino",
    "كريب أجبان": "Cheese Crepe",
    "ﻛﺮﻳﺐ دﺟﺎج": "Chicken Crepe",
    "ﻛﺮﻳﺐ ﺗﻮﻧﺔ": "Tuna Crepe",
    "كريب نوتيلا": "Nutella Crepe",
    "كريب فيوتوتشيني": "Fettuccine Crepe",
    "بانجويني قمبري": "Shrimp Linguine",
    "لانجويني قمبري": "Shrimp Linguine",
    "الافطار من (8ص الى 1م)": "Breakfast (8 AM to 1 PM)",
    "الغداء (من الساعه 1م)": "Lunch (From 1 PM)",
    "المقبلات": "Appetizers",
    "السلاطات": "Salads",
    "الشوربات": "Soups",
    "باستا": "Pasta",
    "ريزوتو": "Risotto",
    "صفايح": "Safiha",
    "بيتزا": "Pizza",
    "سندوتشات": "Sandwiches",
    "غربي اسماك وبحريات": "Seafood",
    "وجبات اطفال": "Kids' Meals",
    "المطبخ الشرقي": "Oriental Cuisine",
    "غربي اللحوم": "Meat Selection",
    "غربي الدجاج": "Chicken Selection",
    "وجبات فاهيتا": "Fajita Meals",
    "عسل": "Honey",
}

# Description translations (common ones)
desc_map = {
    "ﺑﺮﻳﻮش, أوﻣﻠﻴﺖ, ﻋﺴﻞ, ﻣﺮﺑﻰ, ﺟﺒﻨﺔ, ﻓﻮاﻛﻪ, ﻧﻮﺗﻴﻼ, زﻳﺘﻮن ﻣﺘﺒﻞ, ﻫﺮﻳﺴﺔ, ﺳﻠﺔ ﺧﺒﺰ, ﺷﺎي (أﺧﻀﺮ أو أﺣﻤﺮ)": "Brioche, Omelette, Honey, Jam, Cheese, Fruits, Nutella, Seasoned Olives, Harissa, Bread Basket, Tea (Green or Red)",
    "ﺷﻜﺸﻮﻛﺔ, أوﻣﻠﻴﺖ, ﻗﻼﻳﺔ, ﻣﻨﺎﻗﻴﺶ, أﺟﺒﺎن ﻣﺸﻜﻠﺔ, ﺳﻼﻃﺔ مخلل, زﻳﺘﻮن ﻣﺘﺒﻞ, ﻫﺮﻳﺴﺔ, ﺑﺮﻳﻮش, ﺑﻦ ﻛﻴﻚ, ﻣﺮﺑﻰ, ﻓﻄﻴﺮة ﻣﻐﺮﺑﻴﺔ, ﻧﻮﺗﻴﻼ, ﻋﺴﻞ, ﻳﺎﻏﻮرت، زﺑﺪة, ﺳﻠﺔ ﺧﺒﺰ, ﺑﺮاد ﺷﺎﻫﻲ (أﺧﻀﺮ أو أﺣﻤﺮ) (يكفي 3 أشخاص)": "Shakshouka, Omelette, Qallaya, Manakish, Assorted Cheeses, Pickled Salad, Seasoned Olives, Harissa, Brioche, Pancake, Jam, Moroccan Pie, Nutella, Honey, Yogurt, Butter, Bread Basket, Large Tea Pot (Green or Red) (Serves 3 Persons)",
    "ﺑﺮﻳﻮش , اﻧﺠﻠﻴﺶ ﻛﻴﻚ, ﺑﺸﻤﺎط ﻗﺮﻳﺴﻴﻨﻰ, ﻣﺮﺑﻰ , ﻋﺴﻞ, زﺑﺪة, ﺻﺤﻦ ﺳﻼﻃﺔ, ﻓﻮاﻛﺔ ﻣﺠﻔﻔﺔ, ﻛﻮب ﻋﺼﻴﺮ, ﻗﻬﻮة وﺣﻠﻴﺐ": "Brioche, English Cake, Grissini, Jam, Honey, Butter, Salad Plate, Dried Fruits, Juice Cup, Coffee and Milk",
    "ﻓﻄﻴﺮة ﻣﻐﺮﺑﻴﺔ, ﻋﺴﻞ, ﻣﺮﺑﻰ, زﺑﺪة, ﺑﻴﺾ ﻣﺴﻠﻮق, ﺟﺒﻨﺔ , ﺳﻠﺔ ﺧﺒﺰ, ﺷﺎي (أﺧﻀﺮ أو أﺣﻤﺮ )": "Moroccan Pie, Honey, Jam, Butter, Boiled Egg, Cheese, Bread Basket, Tea (Green or Red)",
    "ﻓﻮل ﻓﻼﻓﻞ, ﺑﺎﺑﺎﻏﻨﻮج, ﺳﻼﻃﺔ ﺣﻤﺺ, ﻣﺨﻠﻞ, ﻟﺒﻨﻪ , ﺳﻠﺔ ﺧﺒﺰ ,ﺷﺎاي )أﺧﻀﺮ أو أﺣﻤﺮ": "Foul, Falafel, Baba Ganoush, Hummus Salad, Pickles, Labneh, Bread Basket, Tea (Green or Red)",
    "ﻓﻮل ﻓﻼﻓﻞ, ﺑﺎﺑﺎﻏﻨﻮج, ﺳﻼﻃﺔ ﺣﻤﺺ, ﻣﺨﻠﻞ, ﻟﺒﻨﻪ , ﺳﻠﺔ ﺧﺒﺰ ,ﺷﺎي )أﺧﻀﺮ أو أﺣﻤﺮ": "Foul, Falafel, Baba Ganoush, Hummus Salad, Pickles, Labneh, Bread Basket, Tea (Green or Red)",
    "ﻟﺤﻢ ﺑﻘﺮ, ﺻﺤﻦ ﺳﻼﻃﺔ ﻣﺸﻜﻞ, ﻫﺮﻳﺴﺔ, زﻳﺘﻮن, ﺳﻠﺔ ﺧﺒﺰ": "Beef, Mixed Salad Plate, Harissa, Olives, Bread Basket",
    "ﺷﻜﺸﻮﻛﺔ ﻣﻊ ﺟﺒﻨﺔ ﻣﻮزارﻳﻼ وﺟﺒﻨﺔ ﺗﺸﻴﺪر, ﺧﻴﺎر وﺟﻴﺮﺟﻴﺮ, زﻳﺘﻮن ﻣﺘﺒﻞ, ﺳﻠﺔ ﺧﺒﺰ, ﺷﺎي (أﺧﻀﺮ أو أﺣﻤﺮ)": "Shakshouka with Mozzarella and Cheddar, Cucumber and Arugula, Seasoned Olives, Bread Basket, Tea (Green or Red)",
    "ﺷﻜﺸﻮﻛﺔ ﻣﻊ ﻣﺮﻗﺎز, ﺟﺒﻨﺔ, ﺧﻀﺮوات, زﻳﺘﻮن ﻣﺘﺒﻞ, ﺳﻠﺔ ﺧﺒﺰو ﺷﺎي (أﺧﻀﺮ أو اﺣﻤﺮ)": "Shakshouka with Merguez, Cheese, Vegetables, Seasoned Olives, Bread Basket and Tea (Green or Red)",
    "ﺷﻜﺸﻮﻛﺔ ﺑﻘﺪﻳﺪ, ﺟﺒﻨﺔ, ﺧﻀﺮوات, زﻳﺘﻮن ﻣﺘﺒﻞ, ﺳﻠﺔ ﺧﺒﺰ, ﺷﺎي (أﺧﻀﺮ أو اﺣﻤﺮ)": "Shakshouka with Qadeed, Cheese, Vegetables, Seasoned Olives, Bread Basket, Tea (Green or Red)",
    "ﺑﻴﺾ ﻣﻊ ﻫﺮﻳﺴﺔ, زﻳﺘﻮن, ﻃﻤﺎﻃﻢ، ﺧﻴﺎر، ﺟﺮﺟﻴﺮ و ﺳﻠﺔ ﺧﺒﺰ.": "Eggs with Harissa, Olives, Tomatoes, Cucumber, Arugula and Bread Basket.",
    "ﺑﻴﺾ وﺟﺒﻨﺔ ﻣﻊ ﻫﺮﻳﺴﺔ, زﻳﺘﻮن, ﻃﻤﺎﻃﻢ، ﺧﻴﺎر، ﺟﺮﺟﻴﺮ و ﺳﻠﺔ": "Eggs and Cheese with Harissa, Olives, Tomatoes, Cucumber, Arugula and Basket",
    "ﺑﻴﺾ, ﻓﻠﻔﻞ ﺣﻠﻮ, ﺑﺼﻞ, ﺟﺒﻨﺔ, ﺟﺮﺟﻴﺮ, ﻃﻤﺎﻃﻢ، ﺧﻴﺎر , زﻳﺘﻮن و ﺳﻠﺔ ﺧﺒﺰ.": "Eggs, Bell Pepper, Onion, Cheese, Arugula, Tomatoes, Cucumber, Olives and Bread Basket.",
    "ﺑﻴﺾ, ﻓﻠﻔﻞ ﺣﻠﻮ, ﻓﻘﺎع, ﺟﺒﻨﺔ، زﻳﺘﻮن, ﻃﻤﺎﻃﻢ, ﺧﻴﺎر, ﻫﺮﻳﺴﺔ, و ﺳﻠﺔ ﺧﺒﺰ.": "Eggs, Bell Pepper, Mushroom, Cheese, Olives, Tomatoes, Cucumber, Harissa, and Bread Basket.",
    "ﺗﻮﺳﺖ ﻣﻊ ﺟﺒﻨﺔ ﻛﺮﻳﻢ,ﻣﻮزارﻳﻼ و ﺟﺒﻨﺔ زﻋﺘﺮ.": "Toast with Cream Cheese, Mozzarella and Zaatar Cheese.",
    "ﺗﻮﺳﺖ ﺗﻮﻧﺔ, ﺟﺒﻨﺔ, ﻃﻤﺎﻃﻢ, ﺟﺮﺟﻴﺮ, زﻳﺘﻮن أﺳﻮد, زﻳﺘﻮن ﻣﺘﺒﻞ و ﻫﺮﻳﺴﺔ.": "Tuna Toast, Cheese, Tomatoes, Arugula, Black Olives, Seasoned Olives and Harissa.",
    "ﺗﻮﺳﺖ ﺑﻴﺾ ﻣﻘﻠﻲ, ﺟﺒﻨﺔ, ﻃﻤﺎﻃﻢ, ﺟﺮﺟﻴﺮ, زﻳﺘﻮن أﺳﻮد, زﻳﺘﻮن ﻣﺘﺒﻞ وﻫﺮﻳﺴﺔ.": "Fried Egg Toast, Cheese, Tomatoes, Arugula, Black Olives, Seasoned Olives and Harissa.",
    "ﺗﻮﺳﺖ ﺳﻼﻣﻲ, ﺟﺒﻨﺔ, ﻃﻤﺎﻃﻢ, ﺟﺮﺟﻴﺮ ،زﻳﺘﻮن ﺷﺮاﺋﺢ أﺳﻮد, زﻳﺘﻮن ﻣﺘﺒﻞ وﻫﺮﻳﺴﺔ.": "Salami Toast, Cheese, Tomatoes, Arugula, Sliced Black Olives, Seasoned Olives and Harissa.",
    "ﺑﻴﺠﻞ ﺟﺒﻨﺔ ﻛﺮﻳﻢ, ﺳﻼﻣﻲ, ﻃﻤﺎﻃﻢ و ﺟﺮﺟﻴﺮ.": "Bagel with Cream Cheese, Salami, Tomatoes and Arugula.",
    "بيجل بيض جبنة كريم , طماطم, جرجير, جبنة شرائح": "Bagel with Eggs, Cream Cheese, Tomatoes, Arugula, Sliced Cheese",
    "ﺑﻴﺠﻞ ﺗﻮﻧﺔ, ﻃﻤﺎﻃﻢ و ﺟﺮﺟﻴﺮ": "Bagel with Tuna, Tomatoes and Arugula",
    "بيجل أجبان جبنة شرائح, موزاريلا, جبنة كريم, جرجير و طماطم": "Cheese Bagel Sliced Cheese, Mozzarella, Cream Cheese, Arugula and Tomatoes",
    "ﺑﻴﺾ ﻣﺴﻠﻮق, ﺗﻮﻧﺔ, ﺻﺤﻦ ﻓﻮاﻛﺔ, ﺷﻮﻓﺎن ﺣﻠﻴﺐ, ﺗﻮﺳﺖ ﺷﻌﻴﺮ و ﻳﻐﻮرت و ﺗﻤﺮ.": "Boiled Eggs, Tuna, Fruit Plate, Oatmeal with Milk, Barley Toast, Yogurt and Dates.",
    "ﺑﻴﺎض ﺑﻴﺾ, ﻓﻮل ﺑﺎﻟﻴﻤﻮن, ﺗﻮﺳﺖ ﺷﻌﻴﺮ, ﻓﺮوﺗﺔ و ﻳﻐﻮرت.": "Egg Whites, Foul with Lemon, Barley Toast, Fruit and Yogurt.",
    "ﺻﺤﻦ ﺷﻮﻓﺎن ﻣﻊ اﻟﻤﻜﺴﺮات, ﺗﻤﺮ و ﻓﻮاﻛﺔ.": "Oatmeal Bowl with Nuts, Dates and Fruits.",
    "ﺻﺤﻦ ﻳﺤﺘﻮي ﻋﻠﻰ ﻣﺠﻤﻮﻋﺔ ﻣﺘﻨﻮﻋﺔ ﻣﻦ اﻷﺟﺒﺎن": "A plate containing a variety of cheeses",
    "-2اﻟﺰﻋﺘﺮ ﻣﻊ زﻳﺖ اﻟﺰﻳﺘﻮن": "Zaatar with Olive Oil",
    "ﺟﺒﻨﺔ ﻣﻮزارﻳﻼ, ﺟﺒﻨﺔ ﺷﻴﺪر و ﻃﻤﺎﻃﻢ": "Mozzarella Cheese, Cheddar Cheese and Tomato",
    "ﺧﻀﺮوات, ﺟﺒﻨﺔ, ﻓﻠﻔﻞ ﺣﻠﻮ,ﻃﻤﺎﻃﻢ, زﻳﺘﻮن و ﺑﺼﻞ": "Vegetables, Cheese, Bell Pepper, Tomato, Olives and Onion",
    "ﺟﺒﻨﺔ, ﻓﻘﺎع, ﻃﻤﺎﻃﻢ و ﺑﺼﻞ.": "Cheese, Mushroom, Tomato and Onion.",
    "ﺟﺒﻨﺔ, ﺗﻮﻧﺔ, ﻃﻤﺎﻃﻢ و ﺑﺼﻞ.": "Cheese, Tuna, Tomato and Onion.",
    "ﺻﻠﺼﺔ, ﺟﺒﻨﺔ , ﻓﻘﺎع , ﺳﻼﻣﻲ وﺣﺒﻖ.": "Sauce, Cheese, Mushroom, Salami and Basil.",
    "ﺻﻠﺼﺔ ﺧﻀﺮاء, ﺟﺒﻨﺔ, ﻟﻮز ﺧﺰاﻳﻨﻲ": "Green Sauce, Cheese, Almonds",
    "ﻛﻮاﺗﺮو ﻓﻮرﻣﺎﺟﻮ أرﺑﻌﺔ اﻧﻮاع ﻣﻦ ﺟﺒﻨﺔ": "Quattro Formaggio Four Types of Cheese",
    "ﺻﻠﺼﺔ, ﺟﺒﻨﺔ, دﺟﺎج": "Sauce, Cheese, Chicken",
    "ﺻﻠﺼﺔ ﺑﻴﻀﺎ, ﺟﺒﻨﺔ و ﺟﺒﻤﺒﺮى.": "White Sauce, Cheese and Shrimp.",
    "ﺣﺴﺐ اﻟﻤﻮﺳﻢ": "According to season",
    "يكفي 3 أشخاص": "Serves 3 persons",
    "ﺗﻘﺪم ﻣﻊ أرز ﺑﻄﺎﻃﺔ ﻣﺤﻤﺮة ﺧﻀﺎر ﺳﻮﺗﻲ": "Served with Rice, Fried Potato, Sautéed Vegetables",
    "وزن اللحمة 600ج شخصين": "Meat weight 600g for two people",
    "( ﺧﻮخ / ﻧﻌﻨﺎع / قرفة / ﺗﻮت )": "( Peach / Mint / Cinnamon / Berry )",
    "( كلاسيك / كراميل / فانيليا )": "( Classic / Caramel / Vanilla )",
    "( ﻛﺮاﻣﻴﻞ / ﻓانيليا / ﺑﻨﺪق )": "( Caramel / Vanilla / Hazelnut )",
    "( نوتيلا/ فستق/ عسل ولوز/ لوتس/ عسل / اوريو / فواكه )": "( Nutella / Pistachio / Honey & Almond / Lotus / Honey / Oreo / Fruits )",
    "صدر دجاج متبل بالأعشاب والفلفل الحار و البصل ، الطماطم وخبز مكسيكان ساور كريم ، بيقو ديقالو ، ارز مكسيكان ، جبنة شيدر مكس": "Herb-marinated chicken breast with chili, onions, tomatoes, Mexican bread, sour cream, pico de gallo, Mexican rice, and mixed cheddar cheese.",
    "لحم بقري مشوي متبل بالأعشاب فلفل الوان ، بصل ، طماطم، خبز مكسيكان ، ارز مكسيكان ،ساور كريم ، بيقو ميقالو ، شيدر مكس": "Grilled herb-marinated beef with bell peppers, onions, tomatoes, Mexican bread, Mexican rice, sour cream, pico de gallo, and mixed cheddar cheese.",
    "مكس صدر دجاج مشوي ، لحم بقري مشوي مع فلفل الوات ، بصل ، طماطم ، ارز مكسيكان ، ساور كريم ، بيقو ديقالو ، شيدر مكس": "Mixed grilled chicken breast and beef with bell peppers, onions, tomatoes, Mexican rice, sour cream, pico de gallo, and mixed cheddar cheese.",
    "(ﻓﺮاوﻟﺔ ,ﻣﺎﻧﺠﺎ, ﻣﻮز )": "( Strawberry, Mango, Banana )",
    "حسب الطلب": "As requested",
    "فراولة ﻣﺎﻧﺠﺎ أﻧﺎﻧﺎس دﻻع": "Strawberry, Mango, Pineapple, Watermelon",
    "ﺑﻴﺒﺴﻲ ﻣﺎرﻳﻨﺪا ﺷﺎﻧﻲ ﺳﻔﻦ أب": "Pepsi, Miranda, Shani, 7-Up",
    "( احمر / اخضر )": "( Red / Green )",
    "(كراميل - بندق - فانيلا)": "( Caramel - Hazelnut - Vanilla )",
    "(واﻳﺖ دارك)": "( White - Dark )",
    "(ﺗﻘﺪم ﻣﻊ ﻋﺴﻞ وزﻳﺘﻮن ﻣﻐﺮﺑﻲ)": "( Served with honey and Moroccan olives )",
    "ﻛﺒﺎب ﻟﺤﻢ + ﺷﻴﺶ ﻃﺎووق": "Meat Kebab + Shish Taouk",
    "ﻛﺒﺎب ﻟﺤﻢ + ﺷﻴﺶ ﻃﺎووق + ﺷﻴﺶ ﻟﺤﻢ ﻋﺠﻞ": "Meat Kebab + Shish Taouk + Veal Shish",
    "ﻛﺒﺎب ﻟﺤﻢ + ﺷﻴﺶ ﻃﺎووق + ﺷﻴﺶ ﻟﺤﻢ + ﻛﺒﺎب دﺟﺎج": "Meat Kebab + Shish Taouk + Beef Shish + Chicken Kebab",
    "ﻛﺒﺎب ﻟﺤﻢ +ﻛﺒﺎب دﺟﺎج +ﺷﻴﺶ ﻃﺎووق + ﺷﻴﺶ ﻟﺤﻢ ﻋﺠﻞ + ﻛﺒﺎب اورﻓﻠﻲ": "Meat Kebab + Chicken Kebab + Shish Taouk + Veal Shish + Urfali Kebab",
    "ﻛﺒﺎب ﻟﺤﻢ + ﻛﺒﺎب دﺟﺎج + ﺷﻴﺶﻃﺎووق + ﺷﻴﺶ ﻟﺤﻢ ﻋﺠﻞ + ﻛﺒﺎب اورﻓﻠﻲ+ ﻛﺒﺎب ﺣﺎر + ﺟﻮاﻧﺢ + ﺻﻔﻴﺤﺔ + ﺻﺤﻦ ﺳﻼﻃﺔ": "Meat Kebab + Chicken Kebab + Shish Taouk + Veal Shish + Urfali Kebab + Spicy Kebab + Wings + Safiha + Salad Plate",
    "2 ﻛﺒﺎب ﻟﺤﻢ + 2 ﻛﺒﺎب دﺟﺎج + 2 ﺷﻴﺶ ﻃﺎووق + 2ﺷﻴﺶ ﻟﺤﻢ ﻋﺠﻞ + 2 أرﻳﺎش ﺧﺮوف + 2 ﺟﻮاﻧﺢ + 2 أﻓﺨﺎد دجاج + 1 ﺻﻔﻴﺤﺔ ﺣﺴﺐ اﻟﻄﻠﺐ + 1 ﺻﺤﻦ سلاطة": "2 Meat Kebab + 2 Chicken Kebab + 2 Shish Taouk + 2 Veal Shish + 2 Lamb Chops + 2 Wings + 2 Chicken Thighs + 1 Safiha as requested + 1 Salad Plate",
    "( مارس , كندر , سنكرز )": "( Mars, Kinder, Snickers )",
    "(ﺻﻮص اﺣﻤﺮ ﺻﻮص اﺑﻴﺾﺻﻮص ﺑﻴﻨﻚ)": "( Red / White / Pink Sauce )",
    "حوتة قاروص (سي باص )": "Sea Bass (Sea Bass)",
    "عسل": "Honey",
}

def translate_desc(text):
    if not text: return ""
    # Try exact match
    if text in desc_map: return desc_map[text]
    # Simple search and replace for mixed descriptions
    translated = text
    for ar, en in desc_map.items():
        if ar in translated:
            translated = translated.replace(ar, en)
    return translated

with open("the_menu.json", "r", encoding="utf-8") as f:
    data = json.load(f)

for cat in data:
    cat["en_name"] = translation_map.get(cat["name"], cat["name"])
    
    # Process Direct Items
    for item in cat.get("items", []):
        item["en_name"] = translation_map.get(item["name"], item["name"])
        item["en_desc"] = translate_desc(item.get("desc", ""))
        
    # Process Subcategories
    for sub in cat.get("subcategories", []):
        sub["en_name"] = translation_map.get(sub["name"], sub["name"])
        for item in sub.get("items", []):
            item["en_name"] = translation_map.get(item["name"], item["name"])
            item["en_desc"] = translate_desc(item.get("desc", ""))

with open("the_menu_bilingual.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print("Bilingual JSON generated successfully.")
