<?php
/**
 * Sync variants from JSON_DATA_START.txt into the database.
 * Finds items by en_name + category and adds/updates their variants.
 */
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/Database.php';
require_once __DIR__ . '/../includes/helpers.php';

set_time_limit(300);
ini_set('memory_limit', '256M');
ini_set('display_errors', '1');
error_reporting(E_ALL);
ob_implicit_flush(true);
@ob_end_flush();

$db = Database::getInstance();

// 1. Read the cleaned JSON file (generated by Python from JSON_DATA_START.txt)
$filePath = __DIR__ . '/../the_menu_updated.json';
if (!file_exists($filePath)) die("the_menu_updated.json not found — run the Python extraction first\n");

$menuData = json_decode(file_get_contents($filePath), true);
if (!is_array($menuData)) die("JSON parse error: " . json_last_error_msg() . "\n");

echo "Parsed " . count($menuData) . " categories\n";

// 2. Get current restaurant
$restaurant = $db->query("SELECT id, slug FROM restaurants WHERE slug = 'lavina-house'")->fetch();
if (!$restaurant) die("Restaurant 'lavina-house' not found\n");
$restaurantId = $restaurant['id'];

$totalSynced = 0;
$totalSkipped = 0;

// 3. Process each category
foreach ($menuData as $catData) {
    $catNameEn = $catData['en_name'] ?? '';

    echo "Category: {$catNameEn}... ";
    try {
    $stmt = $db->prepare("SELECT id, name_en FROM categories WHERE restaurant_id = ? AND name_en = ?");
    $stmt->execute([$restaurantId, $catNameEn]);
    $cat = $stmt->fetch();
    // If not found, try matching by Arabic name
    if (!$cat && !empty($catData['name'])) {
        $stmt = $db->prepare("SELECT id, name_en FROM categories WHERE restaurant_id = ? AND name_ar = ?");
        $stmt->execute([$restaurantId, $catData['name']]);
        $cat = $stmt->fetch();
    }
    if (!$cat) {
        echo "  SKIP: Category not found — en='{$catNameEn}', ar='{$catData['name']}'\n";
        // Show available categories in DB
        $all = $db->query("SELECT name_en FROM categories WHERE restaurant_id = $restaurantId")->fetchAll(PDO::FETCH_COLUMN);
        echo "  DB categories: " . implode(', ', $all) . "\n";
        continue;
    }
    $categoryId = $cat['id'];

    // Process direct items
    if (!empty($catData['items'])) {
        echo count($catData['items']) . " items... ";
        syncItems($db, $catData['items'], $categoryId, null, $totalSynced, $totalSkipped, $restaurantId);
    }

    // Process subcategories
    if (!empty($catData['subcategories'])) {
        echo count($catData['subcategories']) . " subs... ";
        foreach ($catData['subcategories'] as $subData) {
            $subNameEn = $subData['en_name'] ?? '';
            $stmt = $db->prepare("SELECT id FROM subcategories WHERE category_id = ? AND name_en = ?");
            $stmt->execute([$categoryId, $subNameEn]);
            $sub = $stmt->fetch();
            $subId = $sub ? $sub['id'] : null;

            if (!empty($subData['items'])) {
                syncItems($db, $subData['items'], $categoryId, $subId, $totalSynced, $totalSkipped, $restaurantId);
            }
        }
    }
    echo "OK\n";
    } catch (Exception $e) { echo " ERROR: " . $e->getMessage() . "\n"; }
}

echo "\n=== Done ===\n";
echo "Variants synced: {$totalSynced}\n";
echo "Items skipped (already had variants): {$totalSkipped}\n";

/**
 * Sync items and their variants with the database.
 */
function syncItems($db, $items, $categoryId, $subId, &$synced, &$skipped, $restaurantId) {
    foreach ($items as $itemData) {
        if (empty($itemData['variants']) || !is_array($itemData['variants'])) continue;

        $itemNameEn = $itemData['en_name'] ?? '';
        $itemNameAr = $itemData['name'] ?? '';

        // Find matching item in DB
        if ($subId) {
            $stmt = $db->prepare("SELECT id FROM items WHERE category_id = ? AND subcategory_id = ? AND en_name = ?");
            $stmt->execute([$categoryId, $subId, $itemNameEn]);
        } else {
            $stmt = $db->prepare("SELECT id FROM items WHERE category_id = ? AND subcategory_id IS NULL AND en_name = ?");
            $stmt->execute([$categoryId, $itemNameEn]);
        }
        $item = $stmt->fetch();

        if (!$item) {
            echo "  NOT FOUND: '{$itemNameEn}' — checking DB items in this category...\n";
            // Show items that are in this category
            $allItems = $db->prepare("SELECT id, name_en FROM items WHERE category_id = ? AND " . ($subId ? "subcategory_id = ?" : "subcategory_id IS NULL"));
            if ($subId) $allItems->execute([$categoryId, $subId]);
            else $allItems->execute([$categoryId]);
            $names = $allItems->fetchAll(PDO::FETCH_COLUMN, 1);
            echo "  DB items: " . implode(', ', array_slice($names, 0, 10)) . "\n";
            continue;
        }

        $itemId = $item['id'];

        // Check if item already has variants
        $existingCount = $db->prepare("SELECT COUNT(*) FROM variants WHERE item_id = ?");
        $existingCount->execute([$itemId]);
        $count = $existingCount->fetchColumn();

        if ($count > 0) {
            $skipped++;
            echo "  SKIP (already has {$count} variants): {$itemNameEn}\n";
            continue;
        }

        // Insert variants
        $sortOrder = 0;
        $inserted = 0;
        foreach ($itemData['variants'] as $varData) {
            $sortOrder++;

            // Handle inconsistent variant naming
            $varNameAr = $varData['name'] ?? $varData['variant_name'] ?? '';
            $varNameEn = $varData['en_name'] ?? $varData['variant_en_name'] ?? '';

            if (empty($varNameAr) && empty($varNameEn)) continue;

            $varPrice = null;
            if (!empty($varData['price'])) {
                $varPrice = parsePriceString($varData['price']);
            }

            $stmt = $db->prepare(
                "INSERT INTO variants (item_id, name_ar, name_en, price, desc_ar, desc_en, image, sort_order)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
            );
            $stmt->execute([
                $itemId,
                $varNameAr,
                $varNameEn,
                $varPrice,
                $varData['desc'] ?? '',
                $varData['en_desc'] ?? '',
                $varData['image'] ?? null,
                $sortOrder
            ]);
            $inserted++;
        }

        if ($inserted > 0) {
            $synced++;
            echo "  SYNCED {$inserted} variants → {$itemNameEn}\n";
        }
    }
}
